### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by schiller256** [apispoint/soter#1]
This link produce a error https://soter-reference-artifacts.apispoint.com/

Error details: The Amazon CloudFront distribution is configured to block access from your country

My current country is Germany.

**Comment by gibbonsj** [comment]
_Regarding international regulation including the European Union (EU) General Data Protection Regulation (GDPR)_

SO+ER is designed to send information from the sensor to the cloud for processing. The cloud servers are hosted in the US. As a result, we made the difficult decision to limit SO+ER to the US only.

We are exploring the options to remove geographic restrictions at this time.
